name: dark_notepad
description: A beautiful cross-platform notepad application with cloud sync and PDF export.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and styling
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  
  # Other utilities
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
